In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

##REad the dataset
df=pd.read_csv('height-weight.csv')
df.head()

Weight  Height
0      45     120
1      58     135
2      48     123
3      60     145
4      70     160

In [2]:
plt.scatter(df['Weight'],df['Height'])
plt.xlabel("Weight")
plt.ylabel("Height")

Text(0, 0.5, 'Height')

In [3]:
##divide our dataset into independent and dependent features
X=df['Weight']
y=df['Height']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)
#These two lines split your dataset into training and testing sets using Scikit-Learn’s 
# train_test_split() function.
#means 20% of the data is used for testing, and 80% is used for training

X_train,y_train # x_train will print weight with index while y_train will print height with weight

(12    105
 1      58
 13    100
 5      78
 2      48
 11     95
 20     45
 3      60
 4      70
 18     76
 16     50
 21     56
 22     72
 7      90
 10     82
 14     85
 19     87
 6      80
 Name: Weight, dtype: int64,
 12    175
 1     135
 13    183
 5     162
 2     123
 11    182
 20    129
 3     145
 4     160
 18    150
 16    140
 21    140
 22    160
 7     175
 10    176
 14    170
 19    167
 6     163
 Name: Height, dtype: int64)

In [4]:
print(y_test)
print(X_train.shape)  # If X_train is a DataFrame




15    177
9     170
0     120
8     182
17    159
Name: Height, dtype: int64
(18,)


In [5]:
## Standardize the dataset            INTERVIEW QUESTION
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()            #initialise z score formula = (xi - mew)/sigma
#earlier it was giving error because dataset was 1d so below we concert into 2d
X_train = X_train.to_frame()  # Yes, StandardScaler does not work with 1D arrays.
X_test = X_test.to_frame()
X_train=scaler.fit_transform(X_train)  
X_test=scaler.transform(X_test)    #transform se x_train ka hi mew and s.deviation use hoga
#fit_transform se khud ka mew aur sigma use hoga which will leaad to data leakage ,
#  hm nhi chahte ki training data ko test data k baare m kuch bhi pta chale


In [6]:

X_test

array([[ 0.21043706],
       [ 0.21043706],
       [-1.6552288 ],
       [ 1.17153765],
       [-0.52452222]])

In [7]:
plt.scatter(X_train,y_train)

In [8]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor



LinearRegression()

In [9]:
type(X_train)

numpy.ndarray

In [10]:
X_train=np.array(X_train).reshape(-1,1)
X_test=np.array(X_test).reshape(-1,1)

In [11]:
y_train.shape

(18,)

In [12]:
regressor.fit(X_train,y_train) #The .fit() method trains the model on the provided dataset.

LinearRegression()

In [13]:
## coefficient and intercepts
print("Coefficient : ",regressor.coef_)
print("Intercept : ",regressor.intercept_)

Coefficient :  [17.03440872]
Intercept :  157.5


In [14]:
plt.scatter(X_train,y_train)
plt.plot(X_train,regressor.predict(X_train))  #regressor.predict(X_train): This part uses
#the trained model (regressor) to make predictions on the X_train data.

### prediction of train data
1. predicted height output= intercept +coef_(Weights)
2. y_pred_train =65.4364 + 1.26(X_train)
          
### prediction of test data
1. predicted height output= intercept +coef_(Weights)
2. y_pred_test =65.4364 + 1.26(X_test)

In [15]:
y_pred_test=regressor.predict(X_test)  #predicting output

In [16]:
y_test

15    177
9     170
0     120
8     182
17    159
Name: Height, dtype: int64

In [17]:
plt.scatter(X_test,y_test)
plt.plot(X_test,regressor.predict(X_test))

In [18]:
### Performance metrics

from sklearn.metrics import mean_squared_error,mean_absolute_error

In [19]:
mse=mean_squared_error(y_test,y_pred_test)
mae=mean_absolute_error(y_test,y_pred_test)
rmse=np.sqrt(mse)
print(mse)
print(mae)
print(rmse)

109.77592599051654
9.822657814519227
10.477400726827076


## R square 
Formula

**R^2 = 1 - SSR/SST**


R^2	=	coefficient of determination
SSR	=	sum of squares of residuals
SST	=	total sum of squares

In [20]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred_test)
print(score)

0.7769869860423441


**Adjusted R2 = 1 – [(1-R2)*(n-1)/(n-k-1)]**

where:

R2: The R2 of the model
n: The number of observations
k: The number of predictor variables

In [21]:
#display adjusted R-squared
1 - (1-score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

0.7026493147231254

In [22]:
regressor.predict(scaler.transform([[75]]))
#predicting output for random , so first we will have to transform it by z score

c:\Users\Abhinav\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([158.19553315])

In [23]:
## Assumptions

## plot a scatter plot for the prediction
plt.scatter(y_test,y_pred_test)



In [24]:
## Residuals
residuals=y_test-y_pred_test

residuals



15    15.915329
9      8.915329
0     -9.304156
8      4.543549
17    10.434926
Name: Height, dtype: float64

In [25]:
## Plot this residuals 
import seaborn as sns
sns.displot(residuals,kind="kde")



In [26]:
## Scatter plot with respect to prediction and residuals
## uniform distribution
plt.scatter(y_pred_test,residuals)

## Using OLS

In [27]:
import statsmodels.api as sm

In [28]:
model = sm.OLS(y_train, X_train).fit()
predictions = model.predict(X_test) 

In [29]:
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:                 Height   R-squared (uncentered):                   0.012
Model:                            OLS   Adj. R-squared (uncentered):             -0.047
Method:                 Least Squares   F-statistic:                             0.1986
Date:                Wed, 05 Mar 2025   Prob (F-statistic):                       0.661
Time:                        13:26:13   Log-Likelihood:                         -116.62
No. Observations:                  18   AIC:                                      235.2
Df Residuals:                      17   BIC:                                      236.1
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

c:\Users\Abhinav\anaconda3\Lib\site-packages\scipy\stats\_axis_nan_policy.py:531: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=18
  res = hypotest_fun_out(*samples, **kwds)


In [30]:
regressor.coef_

array([17.03440872])